import { PlatformKey } from "../platforms";

export interface RawTicket {
  campaignId: number;
  campaignName: string;
  flightStartDate: string;
  flightEndDate: string;
  overallBudget: number;
  objective: string;
  goal: string;
  goalTypeCode: string;
  goalAmount: number;
  vertical: string;
  platforms: PlatformKey[];
}

/**
 * Mock ticketing system data -- the source of truth for campaign metadata (budget, flight
 * dates, objective, goal). One ticket per Campaign ID, 1:1 with the Campaign IDs used in the
 * mock Google Sheet performance data. 10118, 10119, and 10120 have flight start dates after
 * MOCK_TODAY (2026-07-05) and intentionally have no matching sheet rows -- they're the
 * new/pre-launch tickets that drive the cold-start agent flow.
 */
export const TICKETS_DATA: RawTicket[] = [
  {
    campaignId: 10101,
    campaignName: "SpringSaleApparel",
    flightStartDate: "2026-05-10",
    flightEndDate: "2026-07-22",
    overallBudget: 180000,
    objective: "Page Views / Site Traffic",
    goal: "15,000 page views",
    goalTypeCode: "PV",
    goalAmount: 15000,
    vertical: "fitness apparel",
    platforms: ["META", "GOOGLE", "STACKADAPT"],
  },
  {
    campaignId: 10102,
    campaignName: "SummerSneakerLaunch",
    flightStartDate: "2026-05-09",
    flightEndDate: "2026-07-27",
    overallBudget: 650000,
    objective: "Brand Awareness",
    goal: "1,000,000 impressions",
    goalTypeCode: "AWR",
    goalAmount: 1000000,
    vertical: "footwear",
    platforms: ["META", "LINKEDIN", "GOOGLE", "TABOOLA", "STACKADAPT"],
  },
  {
    campaignId: 10103,
    campaignName: "B2BSaaSWebinarQ3",
    flightStartDate: "2026-05-17",
    flightEndDate: "2026-07-23",
    overallBudget: 120000,
    objective: "Page Views / Site Traffic",
    goal: "130,000 page views",
    goalTypeCode: "PV",
    goalAmount: 130000,
    vertical: "B2B SaaS",
    platforms: ["LINKEDIN", "GOOGLE"],
  },
  {
    campaignId: 10104,
    campaignName: "FitnessAppDownloads",
    flightStartDate: "2026-05-19",
    flightEndDate: "2026-07-21",
    overallBudget: 210000,
    objective: "Brand Awareness",
    goal: "4,000,000 impressions",
    goalTypeCode: "AWR",
    goalAmount: 4000000,
    vertical: "fitness tech",
    platforms: ["META", "TABOOLA", "STACKADAPT"],
  },
  {
    campaignId: 10105,
    campaignName: "HomeDecorFallCollection",
    flightStartDate: "2026-05-14",
    flightEndDate: "2026-07-20",
    overallBudget: 175000,
    objective: "Page Views / Site Traffic",
    goal: "15,000 page views",
    goalTypeCode: "PV",
    goalAmount: 15000,
    vertical: "home goods",
    platforms: ["META", "GOOGLE", "LINKEDIN"],
  },
  {
    campaignId: 10106,
    campaignName: "OrganicSkincareLine",
    flightStartDate: "2026-05-19",
    flightEndDate: "2026-07-25",
    overallBudget: 140000,
    objective: "Brand Awareness",
    goal: "1,000,000 impressions",
    goalTypeCode: "AWR",
    goalAmount: 1000000,
    vertical: "beauty",
    platforms: ["META", "STACKADAPT", "TABOOLA"],
  },
  {
    campaignId: 10107,
    campaignName: "CloudSecuritySuite",
    flightStartDate: "2026-05-12",
    flightEndDate: "2026-07-19",
    overallBudget: 260000,
    objective: "Page Views / Site Traffic",
    goal: "90,000 page views",
    goalTypeCode: "PV",
    goalAmount: 90000,
    vertical: "B2B SaaS / cybersecurity",
    platforms: ["LINKEDIN", "GOOGLE", "STACKADAPT"],
  },
  {
    campaignId: 10108,
    campaignName: "PetSupplyAutumnPromo",
    flightStartDate: "2026-05-17",
    flightEndDate: "2026-08-01",
    overallBudget: 95000,
    objective: "Page Views / Site Traffic",
    goal: "25,000 page views",
    goalTypeCode: "PV",
    goalAmount: 25000,
    vertical: "pet products",
    platforms: ["META", "GOOGLE", "TABOOLA"],
  },
  {
    campaignId: 10109,
    campaignName: "EVChargingNetworkAwareness",
    flightStartDate: "2026-05-13",
    flightEndDate: "2026-07-27",
    overallBudget: 850000,
    objective: "Brand Awareness",
    goal: "500,000 impressions",
    goalTypeCode: "AWR",
    goalAmount: 500000,
    vertical: "automotive / EV",
    platforms: ["META", "LINKEDIN", "GOOGLE", "TABOOLA", "STACKADAPT"],
  },
  {
    campaignId: 10110,
    campaignName: "OnlineMBAProgram",
    flightStartDate: "2026-05-08",
    flightEndDate: "2026-07-24",
    overallBudget: 160000,
    objective: "Page Views / Site Traffic",
    goal: "130,000 page views",
    goalTypeCode: "PV",
    goalAmount: 130000,
    vertical: "education",
    platforms: ["LINKEDIN", "GOOGLE"],
  },
  {
    campaignId: 10111,
    campaignName: "CraftBeerSubscriptionBox",
    flightStartDate: "2026-05-14",
    flightEndDate: "2026-07-29",
    overallBudget: 70000,
    objective: "Page Views / Site Traffic",
    goal: "40,000 page views",
    goalTypeCode: "PV",
    goalAmount: 40000,
    vertical: "food & beverage",
    platforms: ["META", "STACKADAPT"],
  },
  {
    campaignId: 10112,
    campaignName: "OutdoorGearBlackFriday",
    flightStartDate: "2026-05-18",
    flightEndDate: "2026-07-25",
    overallBudget: 480000,
    objective: "Page Views / Site Traffic",
    goal: "40,000 page views",
    goalTypeCode: "PV",
    goalAmount: 40000,
    vertical: "outdoor / apparel",
    platforms: ["META", "GOOGLE", "TABOOLA", "STACKADAPT", "LINKEDIN"],
  },
  {
    campaignId: 10113,
    campaignName: "TelehealthPlatformSignup",
    flightStartDate: "2026-05-19",
    flightEndDate: "2026-07-21",
    overallBudget: 520000,
    objective: "Page Views / Site Traffic",
    goal: "60,000 page views",
    goalTypeCode: "PV",
    goalAmount: 60000,
    vertical: "health tech",
    platforms: ["META", "GOOGLE", "LINKEDIN", "TABOOLA", "STACKADAPT"],
  },
  {
    campaignId: 10114,
    campaignName: "LuxuryWatchHolidayCampaign",
    flightStartDate: "2026-05-19",
    flightEndDate: "2026-07-30",
    overallBudget: 220000,
    objective: "Brand Awareness",
    goal: "1,500,000 impressions",
    goalTypeCode: "AWR",
    goalAmount: 1500000,
    vertical: "luxury retail",
    platforms: ["META", "TABOOLA"],
  },
  {
    campaignId: 10115,
    campaignName: "MealKitDeliveryTrial",
    flightStartDate: "2026-05-11",
    flightEndDate: "2026-07-27",
    overallBudget: 390000,
    objective: "Page Views / Site Traffic",
    goal: "15,000 page views",
    goalTypeCode: "PV",
    goalAmount: 15000,
    vertical: "food delivery",
    platforms: ["META", "GOOGLE", "STACKADAPT", "TABOOLA", "LINKEDIN"],
  },
  {
    campaignId: 10116,
    campaignName: "FinTechBudgetingApp",
    flightStartDate: "2026-05-09",
    flightEndDate: "2026-08-02",
    overallBudget: 610000,
    objective: "Brand Awareness",
    goal: "4,000,000 impressions",
    goalTypeCode: "AWR",
    goalAmount: 4000000,
    vertical: "fintech",
    platforms: ["META", "GOOGLE", "LINKEDIN", "STACKADAPT", "TABOOLA"],
  },
  {
    campaignId: 10117,
    campaignName: "YogaRetreat_Bookings",
    flightStartDate: "2026-05-19",
    flightEndDate: "2026-07-31",
    overallBudget: 85000,
    objective: "Page Views / Site Traffic",
    goal: "15,000 page views",
    goalTypeCode: "PV",
    goalAmount: 15000,
    vertical: "wellness / travel",
    platforms: ["META", "GOOGLE"],
  },
  {
    campaignId: 10118,
    campaignName: "WinterCoatLaunch",
    flightStartDate: "2026-07-16",
    flightEndDate: "2026-08-24",
    overallBudget: 300000,
    objective: "Brand Awareness",
    goal: "6,000,000 impressions",
    goalTypeCode: "AWR",
    goalAmount: 6000000,
    vertical: "apparel",
    platforms: ["META", "GOOGLE", "STACKADAPT"],
  },
  {
    campaignId: 10119,
    campaignName: "EnterpriseAIWebinar",
    flightStartDate: "2026-07-17",
    flightEndDate: "2026-09-13",
    overallBudget: 150000,
    objective: "Page Views / Site Traffic",
    goal: "40,000 page views",
    goalTypeCode: "PV",
    goalAmount: 40000,
    vertical: "B2B SaaS",
    platforms: ["LINKEDIN", "GOOGLE"],
  },
  {
    campaignId: 10120,
    campaignName: "HolidayGiftGuide",
    flightStartDate: "2026-07-17",
    flightEndDate: "2026-08-22",
    overallBudget: 400000,
    objective: "Page Views / Site Traffic",
    goal: "130,000 page views",
    goalTypeCode: "PV",
    goalAmount: 130000,
    vertical: "retail",
    platforms: ["META", "TABOOLA", "STACKADAPT", "LINKEDIN"],
  },
];
